### ISSUE TITLE
Could you translate the application completely into English?

### ISSUE THREAD

**Issue by ghost** [rekols/sysbro#1]
could you make a deb compatible with deepin 15.9.2 ? (debian stable)
i can not install in deepin 15.9.2(debian stable) is problem of dependences , the package requires dependence libqt5core5a(>=5.10.0)

or would be better if you make a flatpak ,for resolve this problem of dependences

![DeepinScreenshot_gdebi-gtk_20190324152312](https://user-images.githubusercontent.com/26883220/54886023-c1f23a80-4e48-11e9-961c-cf3a18b00125.png)

please, thank you.

**Comment by reionwong** [comment]
Hi, I compiled on my deepin 15.9.2, my deepin is QT5.10 version, flatpak I won't pack, you can compile and package on your own computer.

You need to install dependencies:

* $ sudo apt install qt5-default fakeroot g++ qttools5-dev-tools libdtkwidget-dev 

Then open the terminal in the source directory:

* $ dpkg-buildpackage -b

**Comment by ghost** [comment]
hi , in deepin 15.9.2 **(debian testing)** works correctly :+1: 
![IMG_20190325_215533](https://user-images.githubusercontent.com/26883220/54971181-e46c7c80-4f4a-11e9-8cda-fbbc27dbfb80.jpg)

but in deepin 15.9.2 beta **(debian stable)** has broken dependencies (libqt5core5a(>=5.10.0)) ,
in future when deepin goes completely to debian stable , you will need to compile it to work with the new base debian
__________________________________________________________________________________
**about the application**
the application is wonderful, I congratulate you.
however, it is not translated completely into English.

![IMG_20190325_215515](https://user-images.githubusercontent.com/26883220/54971253-25649100-4f4b-11e9-96a1-3c23fc957fd2.jpg)

![IMG_20190325_215510](https://user-images.githubusercontent.com/26883220/54971256-2a294500-4f4b-11e9-8962-9e5e59eccc7b.jpg)

![IMG_20190325_215502](https://user-images.githubusercontent.com/26883220/54971257-2bf30880-4f4b-11e9-8fa6-e9f64103403b.jpg)

![IMG_20190325_215452](https://user-images.githubusercontent.com/26883220/54971260-2eedf900-4f4b-11e9-8fcb-3d3a2684f915.jpg)

![IMG_20190325_215445](https://user-images.githubusercontent.com/26883220/54971265-331a1680-4f4b-11e9-8ce7-f618e8985186.jpg)

Could you translate it completely into English? please.

**Comment by reionwong** [comment]
in the works.
