### ISSUE TITLE
mint 19.1上依赖关系不满足

### ISSUE THREAD

**Issue by BluesFu** [rekols/sysbro#10]
mintlinux上该依赖版本：libdtkcore2 已经是最新版 (2.0.7.1-3)。

安装依赖关系不满足：libdtkcore2 (>= 2.0.11)

**Comment by reionwong** [comment]
有几种办法，一种是在自己的系统里打个包，dpkg-buildpackage -b

还有就是编译最新的 dtk : 

https://github.com/linuxdeepin/dtkwidget

https://github.com/linuxdeepin/dtkcore
