### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by lxwndr** [rekols/sysbro#14]
1. Release the dark theme for the application.
2. Allow the application to be translated into other languages.
3. Display CPU GHz in real time.
4. View Mesa Driver version.

Do you work for deepin? Or are you an independent developer?

**Comment by reionwong** [comment]
1. Subsequent development will join.
2. This requires community developers to join.
3. The current design does not allow follow-up information display will add a separate page.
4.I need to understand.

I have been working in deepin, currently still in school, Thank you for your suggestion :)

**Comment by lxwndr** [comment]
You can make the files available here on Git. I can contribute to the translation to Brazilian Portuguese (pt-BR).

To view the Mesa Driver version, you need to use specific applications or install the Mesa utility [sudo apt install mesa-utils] - to view the version [glxinfo | grep "OpenGL version"].

Note: See if you can add your app to the deepin Store (support@deepin.org).
