### ISSUE TITLE
Setup Error v0.9.9

### ISSUE THREAD

**Issue by lxwndr** [rekols/sysbro#15]
Sysbro 0.9.9 has incompatibility with UOS 20 (deepin 20 Alpha); A dependency error occurs - In the previous version of the application, this problem does not occur.

Although UOS 20 is a leak. The system base is practically ready (based on Debian 10 Buster).

**Comment by lxwndr** [comment]
![DeepinScreenshot_deepin-deb-installer_20191127092711](https://user-images.githubusercontent.com/45263160/69727214-d76ae300-1100-11ea-8949-1e5c418e7180.png)
![DeepinScreenshot_deepin-terminal_20191127092800](https://user-images.githubusercontent.com/45263160/69727219-da65d380-1100-11ea-96a0-ab8b18b2f2a4.png)

**Comment by reionwong** [comment]
Uos is not supported at this time.

**Comment by lxwndr** [comment]
Can you make the application compatible with deepin 20?

![Screen Capture_select-area_20200423143022](https://user-images.githubusercontent.com/45263160/80130465-fdd96100-856e-11ea-8ad7-335aec499e82.png)

**Comment by reionwong** [comment]
It is already compatible :) https://github.com/rekols/sysbro/commit/7ee6f7af90dbdf3c810295cc8ffe107e18629266

**Comment by lxwndr** [comment]
@rekols Any predictions of the next version with the corrections?
