### ISSUE TITLE
已经把所有组件手动编译，主程序仍然无法cmake

### ISSUE THREAD

**Issue by shenmo7192** [rekols/sysbro#9]
CMake Error at cmake/FindProcps.cmake:393 (message):
  Library procps for dynamic linking not found.

   REASON: Include directory of procps library not found.
   REASON: Library procps not found.

  You can override location of shared libprocps library and the include
  directory by setting PROCPS_SAHRED_LIBRARY and PROCPS_SHARED_INCLUDE_DIR
  cmake variables.

     PROCPS_SHARED_LIBRARY       specifies full path to the library
                                 (i.e. path to the libprocps.so file)
     PROCPS_SHARED_INCLUDE_DIR   specifies directory which contains
                                 the proc/procps.h header.

  You may achieve this e.g.  by running

   ## cmake -D PROCPS_SHARED_LIBRARY:FILEPATH=/path/to/libprocps.so -D PROCPS_SHARED_INCLUDE_DIR:PATH=/path/to/include/dir .

  

  If you insist on dynamic linkage to shared libprocps, update or patch
  libprocps to export all symbols that application needs.  If you manage your
  solution to be persistent, future proof (in sense of API changes) and
  officially accepted by your GNU/Linux distribution, please contact authors.

  Otherwise consider static linkage to libprocps by setting cmake variable
  PROCPS_STATIC, e.g.  by running

   ## cmake -D PROCPS_STATIC:BOOL=ON .

Call Stack (most recent call first):
  cmake/FindProcps.cmake:411 (fail)
  cmake/FindProcps.cmake:668 (check_failed)
  CMakeLists.txt:44 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/deepin/Downloads/sysbro-master/build/CMakeFiles/CMakeOutput.log"

**Comment by reionwong** [comment]
sudo apt install libprocps-dev

试试

**Comment by shenmo7192** [comment]
完成了
希望把这一条写到readme里面
还有我要在armhf平台编译只能交叉编译么？

**Comment by shenmo7192** [comment]
还有大佬，这个报错信息怎么看啊？百度不到教程啊！

**Comment by reionwong** [comment]
我打算准备把 libprocps 这个库给移除了

**Comment by shenmo7192** [comment]
sysbro
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deepin'
Qt: XKEYBOARD extension not present on the X server.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deepin'
Xlib:  extension "RANDR" missing on display ":0.0".
load translate "/usr/share/dtkwidget/translations/dtkwidget2_zh_CN"
load translate "/usr/share/sysbro/translations/sysbro_zh_CN"
在armhf平台编译完,然而打开的时候提示thisran hou jiu shen me dou mei fa sheng

**Comment by shenmo7192** [comment]
fcitx crashed so no chinese now

**Comment by rekols** [comment]
这个提示可以忽略掉吧
